name: Ping issue assignee
# We have some specific pool of issues we'd like to handle. Sometimes the issue
# has an assignee, but doesn't get any updates for some time. In this case it'd
# be useful to occasionally ping the assignee.

# May be we could use "actions/stale@v*", but I'm not sure if it's possible to
# not set the "stale" label at all. Even so, this action will not ping the
# assignee of the "stale" issue one more time.

on:
  # schedule:
  #   - cron: '0 0 * * *'
  workflow_dispatch:

permissions: read-all

jobs:
  run:
    runs-on: ubuntu-20.04
    # List specific issues with assignee but without updates
    # Note: for some reason gh returns 0 results if the "assignee:*" filter is
    # added, so we have to have to "manually" filter the result.
    name: Ping issue assignee
    steps:
    - name: List issues
      run: |
          issues=$(gh issue list --search '-label:"help wanted" -label:cuda \
          -label:confirmed -label:hip -label:sycl-mlir -label:upstream is:open \
          -label:genx -label:sycl-bindless-images -label:sycl-graph \
          -label:native-cpu' --limit 200 --json assignees --json number \
          --json updatedAt \
          -R https://github.com/intel/llvm.git)
          echo $issues; echo $issues > issues.json

    - name: Filter issues and ping
      run:
          # normally 60, 1 for debug
          days_to_stale=1

          cat issues.json | jq -c '.[]' | while read -r issue; do
            assignees_length=$(echo "$issue" | jq '.assignees | length')
            if [ "$assignees_count" -gt 0 ]; then
              updated_at=$(echo "$issue" | jq -r '.updatedAt')
              updated_at_seconds=$(date -d "$updated_at" +%s)
              difference_days=$(( (current_date - updated_at_seconds) / 86400 ))
              if [ "$difference_days" -gt $days_to_stale ]; then
                issue_number=$(echo "$issue" | jq '.number')
                assignee_logins=$(echo "$issue" | jq -r '.assignees[].login' | sed 's/^/@/' | paste -s -d ' ' -)
                echo "issue \#$issue_number has assignee(s) and was updated more than 60 days ago ($updated_at)."
                comment_message="Hi! There have been no updates for at least the last 60 days, though the ticket has assignee(s).

                $assignee_logins, could you please take one of the following actions
                - Please provide an update if you have any (or just a small comment if you don't have any yet).
                - OR mark this issue with the 'confirmed' label if you have confirmed the problem/request and our team should work on it.
                - OR close the issue if it has been resolved.
                - OR take any other suitable action.

                Thanks!"
                echo $comment_message
              fi
            fi
